# Generated by Django 5.2 on 2026-08-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("state", models.CharField(choices=[("BACKLOG", "Backlog"), ("READY", "Ready"), ("IN_PROGRESS", "In progress"), ("REVIEW", "Review"), ("DONE", "Done")], default="BACKLOG", max_length=16)),
                ("priority", models.CharField(choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")], default="MEDIUM", max_length=8)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assignee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_quests", to="projects.projectmembership")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quests", to="projects.project")),
            ],
        ),
    ]
